#NumPy - Numerical Python


Advantages of Numpy Arrays:

  1. Allows several Mathematical operations
  2. Faster operations

In [1]:
import numpy as np

List vs Numpy - time taken

In [2]:
from time import process_time

Time taken by a list to add '5' to each of its elements

In [3]:
ls = [i for i in range(10000)]

start_time = process_time()

ls = [i+5 for i in ls]

end_time = process_time()

print(end_time-start_time)

0.0016684959999997417


Time taken by a numpy array to add '5' to each of its elements

In [7]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5     # np_array = np_array + 5

end_time = process_time()

print(end_time-start_time)

0.0001701689999995537


#Numpy Arrays

In [8]:
# list
list1 = [1,2,3,5]
print(list1)
type(list1)

[1, 2, 3, 5]


list

In [9]:
# numpy array
np_array = np.array([1,2,3,4,5])
print(np_array) # values will not be separated by commas
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [10]:
# creating a one dimensional array

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
# checking the shape of the array
a.shape

(4,)

In [12]:
# creating a two dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
b.shape

(2, 4)

In [15]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial place holders in numpy array

In [18]:
# creating numpy arrays with zeros

x = np.zeros((3,3)) # 3,3 - dimensions of the array
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#creating a numpy array with ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# create an array with a particular value
z = np.full((2,4),22)
print(z)

[[22 22 22 22]
 [22 22 22 22]]


In [26]:
# creating an identity matrix
a = np.eye((5),dtype = int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [30]:
# create a numpy array with random values

b = np.random.random((3,3))
print(b)  # All these values are floating points ranging from 0-1

[[0.41604245 0.72433749 0.37771213]
 [0.84741578 0.94563782 0.4791937 ]
 [0.04884808 0.02400948 0.63412506]]


In [31]:
# create a numpy array with random values with integer values within a specific range

c = np.random.randint(1,10,(3,3))
print(c)

[[1 2 7]
 [7 7 3]
 [1 5 2]]


In [33]:
# create array of evenly spaced values

d = np.linspace(10,30,5,dtype = int)  # 5 - no of elements
print(d)

[10 15 20 25 30]


In [34]:
# array of evenly spaced values with a step value
e = np.arange(10,30,3)                # 3 - step value
print(e)

[10 13 16 19 22 25 28]


In [36]:
#convert a list into an array

lst = [3,34,45,4,2,43,45]
np_array = np.asarray(lst)
print(np_array)
type(np_array)

[ 3 34 45  4  2 43 45]


numpy.ndarray

In [37]:
#convert a tuple into an array

tup = (3,34,45,4,2,43,45)
np_array = np.asarray(tup)
print(np_array)
type(np_array)

[ 3 34 45  4  2 43 45]


numpy.ndarray

#Analysing a numpy array

In [39]:
c = np.random.randint(10,90,(5,5))
print(c)

[[43 74 64 11 58]
 [51 56 36 57 10]
 [80 64 35 11 32]
 [48 35 28 33 71]
 [50 53 21 61 83]]


In [40]:
# finding array dimensions

print(c.shape)

(5, 5)


In [41]:
# check no of dimensions

print(c.ndim)

2


In [42]:
# number of elements of the numpy array

print(c.size)

25


In [43]:
# data type of the elements in the array

print(c.dtype)

int64


#Mathematical operations in NumPy array

In [44]:
list1 = [1,2,3,3,4,5]
list2 = [6,5,4,7,8]

print(list1 + list2)  # concatenation of lists

[1, 2, 3, 3, 4, 5, 6, 5, 4, 7, 8]


In [50]:
a = np.array([1,2,3,3,4,5])
b = np.array([6,5,4,7,8,9])

print(a + b)  # elementwise addition will take place

[ 7  7  7 10 12 14]


In [52]:
print(a-b)

[-5 -3 -1 -4 -4 -4]


In [53]:
print(a*b)

[ 6 10 12 21 32 45]


In [54]:
print(a/b)

[0.16666667 0.4        0.75       0.42857143 0.5        0.55555556]


In [57]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[ 7  7  7 10 12 14]
[-5 -3 -1 -4 -4 -4]
[ 6 10 12 21 32 45]
[0.16666667 0.4        0.75       0.42857143 0.5        0.55555556]


# Array Manipulation

In [58]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 8]
 [6 0 9]]
(2, 3)


In [60]:
# Transpose of the matrix

tran = np.transpose(array)
print(tran)
print(tran.shape)

[[9 6]
 [9 0]
 [8 9]]
(3, 2)


In [61]:
# Another method for finding transpose of. matrix

trans = array.T
print(trans)
print(trans.shape)

[[9 6]
 [9 0]
 [8 9]]
(3, 2)


In [62]:
 # Reshaping an array

 a = np.random.randint(1,10,(2,3))
 print(a)
 print(a.shape)

[[6 9 8]
 [4 9 5]]
(2, 3)


In [63]:
# reshaping

b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 9]
 [8 4]
 [9 5]]
(3, 2)
